### ISSUE TITLE
Change the profile sorting method

### ISSUE THREAD

**Issue by ermsdev** [ASWWU-Web/mask#78]
We have received official complaints that the popularity sorting encourages comparison between students, and have been asked to change it.

**Comment by ermsdev** [comment]
Ideas
- regularly reset view counts
- apply rate limits and/or view reductions to profiles after a certain measure of views have been reached
- regularly randomize sorting
- show `n` random profiles on front search page, and show profiles alphabetically on super search.
- use rolling view average to determine rank
- sort by some other field with a total order, such as most recently updated, or upcoming birthdays.

**Comment by kadensu** [comment]
Since we don't want to implement anything too complex before the Django migration, for now we'll manually reset view counts. Once we finish migrating to Django, we can implement a more interesting algorithm that keeps users interested in The Mask without it devolving into a popularity contest. This also gives us time to solicit user feedback - what do users use The Mask for? What features/sorting algorithm would they be interested in?

**Comment by ermsdev** [comment]
We might be able to sort over recent profile views and then alphabetically for profiles that were not viewed recently. see (https://stackoverflow.com/questions/6168939/sqlite-query-order-by-case) for more info.

This _might_ be a simple implementation and would prevent profiles from being dropped from search results as they would be if we were to only join with the subset of recent views in the `profileviews` table.

**Comment by kadensu** [comment]
In order to measure the effects of any changes to the sorting algorithm, we can use Google Analytics to determine if user habits change with the new algorithm.

**Comment by stephenermshar** [comment]
We're now collecting more usage information through google analytics to get a baseline before moving forward with regular view count resets.

**Comment by ermsdev** [comment]
More ideas for sorting
- display a small (one page) random subset of profiles first, sorted by view count, and then the remaining profiles using some other sort, such as alphabetical or random.
- sort by least viewed first, or least-recently viewed.

**Comment by ermsdev** [comment]
Random sorting has been applied, profiles without photos set are randomly sorted at the bottom.
